Step by step MailHog Integration
iJackUA/hanami-cookbook pull request #39
Opened 2022-03-14 13:33 UTC by karissekjw

Hey! Came across your Hanami cookbook where you recommended MailHog. Have managed to integrate it successfully and would love to contribute to your cookbook by updating this section so others can contribute from it too :). MailHog also has a UI view where you can view hanami emails in the browser. Was wondering if you would like that to be included in the Mail preview section as well?

Let me know what else I can do to improve on the proposed changes!

Cheers

2022-03-14 14:18 UTC, iJackUA requested changes

2022-03-14 14:19 UTC, iJackUA commented
Thanks for contribution!
I added couple comments.

As for email previews as I remember I thought just to cross-post this guide
https://www.davydovanton.com/2016/05/21/preview-hanami-emails-in-browser/
so leave it out of scope for this PR

2022-03-14 14:39 UTC, karissekjw commented
Thanks for the comments! Definitely learnt something there. I've updated the docs accordingly

2022-03-21 10:44 UTC, merged

2022-03-21 10:45 UTC, iJackUA commented
Merged, thanks again!